name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into VPS and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "[INFO] Atualizando site..."
            find ~/BlackHorses/.git -not -user black-horses -exec chown black-horses:black-horses {} + 2>/dev/null || true
            cd ~/BlackHorses
            git fetch origin
            git reset --hard origin/main
            echo "[INFO] Deploy finalizado com sucesso!"
